---
- name: Add WebUpd8 PPA
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present
    update_cache: yes

- name: Accept Oracle license
  shell:
    echo debconf shared/accepted-oracle-license-v1-1 "{{ item }}" true | debconf-set-selections
  with_items:
    - select
    - seen

- name: Install OracleJDK package
  apt:
    name: "{{ oraclejdk_package }}"
    state: present

- name: Set default JDK
  apt:
    name: "{{ oraclejdk_package | regex_replace('^.*([0-9]).*$', 'oracle-java\\1-set-default') }}"
    state: present
  when: oraclejdk_set_as_default
